server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://192.168.65.129:3306/cloud_order?useSSL=false
    username: root
    password: 5q6W7e8R
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: orderservice
  cloud:
    nacos:
      server-addr: 192.168.65.129:8848    # nacos服务地址
      discovery:
        cluster-name: HZ   #集群名称
        namespace: 77a1fe80-13e9-4470-86e9-e75caed9d4bb # dev环境
        ephemeral: false # 是否是临时实例

mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
#eureka:
#  client:
#    service-url:  # eureka的地址信息
#      defaultZone: http://127.0.0.1:10086/eureka
userservice:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule  # 负载均衡规则  优先现在本地集群
ribbon:
  eager-load:
    enabled: true # 开启饥饿加载
    clients: # 指定饥饿加载的服务名称
      - userservice

#对feign的优化 一个是 引入httpclient 开启连接池  另一个是日志开启级别
feign:
  httpclient:
    enabled: true # 开启feign对HttpClient的支持
    max-connections: 200 # 最大连接数
    max-connections-per-route: 50 # 单个路径的最大连接数
#  client:
#    config:
#      dafault:
#        loggerLevel: FULL   #日志类型配置